# Generated by Django 5.0.6 on 2024-05-13 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='updated_date',
            new_name='updated_at',
        ),
    ]
